### ISSUE TITLE
Maven Central artifact

### ISSUE THREAD

**Issue by timeking** [olap4j/olap4j#39]
Could you build and deploy jar and src.jar to Maven Central repository?

**Comment by buggtb** [comment]
Hi @timeking this initial release was from an old build and was a bit cobbled together. We'll be releasing 1.3.0 shortly which will have the full src/javadoc bundles to go with the jar on maven central.

**Comment by timeking** [comment]
@buggtb, thank you, read last issue about 1.3.0, it is a good news for olap world!

**Comment by buggtb** [comment]
Yeah give us a few days to get our release process sorted and we'll ship
the initial olap4j release candidates

**Comment by julianhyde** [comment]
We now have artifacts for olap4j and olap4j-xmlaserver 1.2.0 on maven central. Marking fixed.
