### ISSUE TITLE
Query Scope Named Sets fail validation

### ISSUE THREAD

**Issue by chubbard** [olap4j/olap4j#49]
This is a big deal for me right now.  Can we get OLAP4J to support Named Sets using the with syntax in MDX queries?

http://jira.pentaho.com/browse/MONDRIAN-877

**Comment by julianhyde** [comment]
I feel your pain. However, it looks as if the bug is in Mondrian, not olap4j.

**Comment by chubbard** [comment]
I don't think that's the case.  I've tracked it back in the code and it's unimplemented in MondrianOlap4jConnection.  See the method MondrianOlap4jConnection.toOlap4j(Exp exp) method.  That's what's throwing the Util.needToImplement() because it isn't translating the NamedSetExp into a ParseTreeNode.  I think that class already exists as WithSetNode, but the connective tissue is missing to instantiate there and translate it.  I don't think this is a Mondrian problem because if you just don't validate the MDX expression it'll work.  It's just this validation of the query that fails.

**Comment by julianhyde** [comment]
The code that is doing the wrong thing is in mondrian.jar and the fix would
be to code in mondrian.jar. That makes it a bug in mondrian's olap4j
driver, not in olap4j.
