### ISSUE TITLE
API docs offline

### ISSUE THREAD

**Issue by t1233** [olap4j/olap4j#57]
At the moment (22. January 2018) the project's website www.olap4j.org seems to be offline/misconfigured.

A request to www.olap4j.org leads to a site starting with "As clever as clever" and "(Julian's home page)".
A request to www.olap4j.org/api results in HTTP 404.

Where could I found the API docs for olap4j?

Thanks in advice,
T1233

**Comment by julianhyde** [comment]
Apologies, and thanks for letting me know. The site is back up now.

My server was overheating and I had to rebuild it. It took several days to get the configuration of Tomcat right. Let me know if you see other problems.
