### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by jon-hanson** [olap4j/olap4j#58]
Judging by the absence of recent releases, the lack of commit activity, and the lack of msg activity on the dev list since mid-2016, it seems to be dead.

**Comment by jon-hanson** [comment]
Update, an answer of sorts is [here](url).

**Comment by buggtb** [comment]
Hey @jon-hanson I wouldn't class it as dead, quite :) Sure there hasn't been any activity on it, but we use it on Saiku and the folks at Pentaho use it. The development has stopped but mostly cause it works. If there are things that need fixing and releasing I'm sure we can grease the wheels with a bit of effort.

**Comment by jon-hanson** [comment]
@buggtb Thanks. I'm asking more out of curiosity than a need for a fix or feature, but do you know what's happening with a post-1.2.0-release?
